version: "3"

services:
  db_users:
    container_name: postgres_users
    build:
      context: ./users/
    ports:
      - "5433:5432"
  db_chats:
    container_name: postgres_chats
    build:
      context: ./chat/
    ports:
      - "5434:5432"
  db_messages:
    container_name: mongo_messages
    build:
      context: ./message/
    ports:
      - "27018:27017"